### ISSUE TITLE
[Translations] Add translations for sorting options

### ISSUE THREAD

**Issue by Hybris95** [Hybris95/UEX-Trader#124]
New translations added

- sort_trade_margin = Trade Margin
- sort_profit_margin = Profit margin
- sort_scu_margin = SCU margin
- sort_distance = Distance
- sort_quantity = Quantity
- sort_oldest_update = Oldest update
- sort_latest_update = Latest update
- sort_buy_latest = Buy latest update
- sort_sell_latest = Sell latest update
- unit_km = km
- unit_qty = µ
- unit_minute = minute
- sort_descending = Descending
- sort_ascending = Ascending
- total_margin_by_distance = Total Margin by Distance
- unit_margin_by_distance = Unit Margin by Distance
- outdated = Outdated
- days = Days
- not_user_trades = Not for User Trades
- minimum = Minimum

**Comment by Hybris95** [comment]
## French :
- sort_trade_margin = Marge de l'Echange
- sort_profit_margin = Marge de Profit
- sort_scu_margin = Marge par SCU
- sort_distance = Distance
- sort_quantity = Quantité
- sort_oldest_update = Plus ancienne mise à jour
- sort_latest_update = Dernière mise à jour
- sort_buy_latest = Dernière mise à jour d'Achat
- sort_sell_latest = Dernière mise à jour de Vente
- unit_km = km
- unit_qty = µ
- unit_minute = minute
- sort_descending = Descendant
- sort_ascending = Ascendant

**Comment by Hybris95** [comment]
https://github.com/Hybris95/UEX-Trader/issues/125 Distance sorting options

**Comment by Hybris95** [comment]
https://github.com/Hybris95/UEX-Trader/issues/106 Outdated sorting/filtering options

**Comment by Hybris95** [comment]
https://github.com/Hybris95/UEX-Trader/issues/151 Minimum total margin filtering option

**Comment by GazAlt** [comment]
sort_trade_margin = Торговая маржа
sort_profit_margin = Рентабельность
sort_scu_margin = Маржа SCU
sort_distance = Расстояние
sort_quantity = Количество
sort_oldest_update = Самое старое обновление
sort_latest_update = Последнее обновление
sort_buy_latest = Последнее обновление покупки
sort_sell_latest = Последнее обновление продажи
unit_km = км
unit_qty = µ
unit_minute = минута
sort_descending = По убыванию
sort_ascending = По возрастанию
total_margin_by_distance = Общая маржа на единицу расстояния
unit_margin_by_distance = Единичная маржа на единицу расстояния
outdated = Устаревшее
days = Дни
not_user_trades = Не для пользовательских торгов
minimum = Минимум
